//Session related Actions
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

export const TEXT_TO_VOICE = 'TEXT_TO_VOICE';

export const FETCH_VOICES_SUCCESS = "FETCH_VOICES_SUCCESS";

export const FETCH_LANGUAGES_SUCCESS = "FETCH_LANGUAGES_SUCCESS";

export const SET_SELECTED_LANGUAGE = 'SET_SELECTED_LANGUAGE';
export const SET_SELECTED_ACCENT = 'SET_SELECTED_ACCENT';

export const GENERATE_VOICE_LOADING = 'GENERATE_VOICE_LOADIN';
export const GENERATE_VOICE_FAILURE = 'GENERATE_VOICE_FAILURE';
export const GENERATE_VOICE_SUCCESS = 'GENERATE_VOICE_SUCCESS';
export const CLEAR_VOICE_URL = "CLEAR_VOICE_URL";

export const SAVE_VOICE_URL = "SAVE_VOICE_URL";