export default {
  headerTitle: 'Speeched',
  login: 'Login',
  signup: 'Sign up',
  or: 'OR',
  start: "Welcome Back!",
  loginText: `We've missed you! Please sign in to catch up on what you've missed`,
  phonePlaceholder: 'Phone number',
  emailPlaceholder: 'Email',
  fullname: 'Full name',
  password: 'Password',
  forgotPassword: 'Forgot Password?',
  noAccount: "Don't have an account, ",
  signupnow: 'Welcome!',
  loginnow: 'LOGIN NOW',
  firstName: 'First Name',
  lastName: 'Last Name',
  next: 'Next',
  logOut: 'Logout',
  firstNamea: 'First Name',
  lastNamea: 'Last Name',
  email: 'Email',
  submit: 'Submit',
  skip: 'Skip',
  skipCapitalCase: 'SKIP',
  home: 'Home',
  oldPassword: 'Type your password',
  newPassword: 'Type your new password',
  confirmPassword:'Confirm Password',
  changePassword:'Change Password'
};
